export enum STEPS {
  PAYMENT_CHECKOUT = "PAYMENT_CHECKOUT",
  PAYPAL_DETAIL = "PAYPAL_DETAIL",
  STRIPE_DETAIL = "STRIPE_DETAIL",
  BOOKED_SUCCESS = "BOOKED_SUCCESS",
  CANCEL_REQUEST = "CANCEL_REQUEST",
}
